version: '3'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: "${PROJECT_NAME}_nginx"
        restart: always
        ports:
            - "${HTTP_PORT}:80"
            - "${SSL_PORT}:443"
        volumes:
            - $PWD/html:/var/www/html
            - $PWD/.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - $PWD/.docker/certs:/etc/ssl
        links:
            - php
        networks:
            - LEMP
        restart: always


    php:
        build: $PWD/.docker/php
        container_name: "${PROJECT_NAME}_php"
        restart: always
        volumes:
            - $PWD/html:/var/www/html
            - $PWD/.docker/php/files/php.ini-production:/usr/local/etc/php/php.ini
        expose:
            - "9000"       
        networks:
            - LEMP
        depends_on: 
            - db
        restart: always


    db:
        image: mysql:5.7
        container_name: "${PROJECT_NAME}_db"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
            MYSQL_DATABASE: "${DB_NAME}"
        ports:
            - "${DB_PORT_EXT}:3306"
        networks:
            - LEMP
        volumes:
            - $PWD/.docker/mysql:/var/lib/mysql
        restart: always
        
networks:
    LEMP:
